### ISSUE TITLE
Cache preloader

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/vuepress#48]
## Goal
Crawl a page for links and preload their contents. If we can do this in the background, we can make Vuepress sites feel very fast.

## Roadmap
- [x] Get list of links whenever route changes
- [x] Sort list according to importance - header/menu/nav links first, etc.
- [x] Cycle through list and load results in background until limit is reached (cache size? certain number of pages crawled per router update?)
- [x] Add easy way to change the arbitrary limit or switch off entirely

**Comment by SaFrMo** [comment]
The`CacheCrawler` is activated in `App.vue` and `src/utils/store.vue` - turn it off in those locations to remove from a site. Implemented in fb184c8.
